# Global EV Transition Readiness Index

## Import Libraries

In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load Datasets

The project uses EV data from the IEA, population and national context data from the World Bank, low-carbon electricity data from OWID, and scraped renewable electricity data from CountryEconomy.

In [38]:
df_iea = pd.read_excel(r"Datasets\EVDataExplorer2025.xlsx", sheet_name="GEVO_EV_2025")
df_population = pd.read_csv(r"Datasets\API_SP\API_SP.POP.TOTL_DS2_en_csv_v2_58.csv", skiprows=4)
df_gdp = pd.read_csv(r"Datasets\API_NY\API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_1700.csv", skiprows=4)
df_electricity = pd.read_csv(r"Datasets\API_EG\API_EG.USE.ELEC.KH.PC_DS2_en_csv_v2_1655.csv", skiprows=4)
df_owid = pd.read_csv(r"Datasets\owid_share_electricity_low_carbon_full.csv")
df_renewable = pd.read_csv(r"Datasets\countryeconomy_renewable_electricity_2024.csv")

## Preview Source Data

In [39]:
df_iea.head()

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World

In [40]:
df_population.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN

In [41]:
df_gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,38116.831099,39278.829727,39652.632070,30347.637185,35104.786804,38979.835825,41964.771191,44558.928759,NaN,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4214.397085,4220.912502,4195.865418,3978.931395,4056.113017,4106.501907,4083.993003,4106.434140,NaN,NaN
2,Afghanistan,AFG,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2952.998916,2902.392113,2927.245144,2769.685745,2144.166570,1981.710168,1983.812620,NaN,NaN,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5999.744780,6016.312217,6059.606024,5687.849988,5690.967743,5806.172890,5874.951080,5996.395736,NaN,NaN
4,Angola,AGO,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,10414.235884,10000.944377,9648.011038,8960.337972,8862.281333,8950.142593,8788.261064,8901.887366,NaN,NaN

In [42]:
df_electricity.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,566.130764,568.138013,550.050979,513.707046,513.465287,502.713913,484.004412,NaN,NaN,NaN
2,Afghanistan,AFG,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,179.985487,181.957492,187.406789,194.981500,201.929224,199.854471,207.456239,NaN,NaN,NaN
4,Angola,AGO,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,315.199297,370.736573,411.266103,439.118174,394.730414,373.031828,379.103010,NaN,NaN,NaN

In [43]:
df_owid.head()

          Entity Code  Year  Share of electricity from low-carbon sources
0  ASEAN (Ember)  NaN  2000                                     19.334143
1  ASEAN (Ember)  NaN  2001                                     19.055025
2  ASEAN (Ember)  NaN  2002                                     17.666613
3  ASEAN (Ember)  NaN  2003                                     16.668121
4  ASEAN (Ember)  NaN  2004                                     15.696422

In [44]:
df_renewable.head()

,country,year,installed_capacity_mw,generation_gwh,renewable_installed_capacity_mw,renewable_installed_capacity_share_pct,renewable_generation_gwh,renewable_generation_share_pct,renewable_generation_change_pct_points,source_url
0,United States,2024,1283644,4392552,451219,35.151413,1068551,24.33,1.34,https://countryeconomy.com/energy-and-environm...
1,United Kingdom,2024,114640,267980,57947,50.546930,140765,52.53,2.24,https://countryeconomy.com/energy-and-environm...
2,Germany,2024,287372,490177,177923,61.913826,279331,56.99,2.48,https://countryeconomy.com/energy-and-environm...
3,France,2024,160877,537227,70084,43.563716,150862,28.08,-0.08,https://countryeconomy.com/energy-and-environm...
4,Japan,2024,353288,907015,126313,35.753550,227883,25.12,-0.41,https://countryeconomy.com/energy-and-environm...

## Check Dataset Size and Structure

In [45]:
# Print the size of each dataset 
print("IEA EV data:", df_iea.shape)
print("Population data:", df_population.shape)
print("GDP data:", df_gdp.shape)
print("Electricity consumption data:", df_electricity.shape)
print("OWID low-carbon electricity data:", df_owid.shape)
print("Scraped renewable electricity data:", df_renewable.shape)

IEA EV data: (16436, 9)
Population data: (266, 71)
GDP data: (266, 71)
Electricity consumption data: (266, 71)
OWID low-carbon electricity data: (7872, 4)
Scraped renewable electricity data: (188, 10)

In [46]:
df_iea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16436 entries, 0 to 16435
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   16436 non-null  object
 1   category         16436 non-null  object
 2   parameter        16436 non-null  object
 3   mode             16436 non-null  object
 4   powertrain       16436 non-null  object
 5   year             16436 non-null  int64
 6   unit             16436 non-null  object
 7   value            16436 non-null  float64
 8   Aggregate group  16436 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.1+ MB

In [47]:
df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [48]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            233 non-null    float64
 35  1991            234 non-null    float64
 36  1992            234 non-null    float64
 37  1993            234 non-null    float64
 38  1994            235 non-null    float64
 39  1995            236 non-null    float64
 40  1996            236 non-null    float64
 41  1997            238 non-null    float64
 42  1998            238 non-null    float64
 43  1999            238 non-null    float64
 44  2000            240 non-null    float64
 45  2001            240 non-null    float64
 46  2002            241 non-null    float64
 47  2003            241 non-null    float64
 48  2004            241 non-null    float64
 49  2005            241 non-null    float64
 50  2006            242 non-null    float64
 51  2007            243 non-null    float64
 52  2008            245 non-null    float64
 53  2009            246 non-null    float64
 54  2010            246 non-null    float64
 55  2011            246 non-null    float64
 56  2012            246 non-null    float64
 57  2013            247 non-null    float64
 58  2014            247 non-null    float64
 59  2015            247 non-null    float64
 60  2016            247 non-null    float64
 61  2017            247 non-null    float64
 62  2018            247 non-null    float64
 63  2019            247 non-null    float64
 64  2020            247 non-null    float64
 65  2021            247 non-null    float64
 66  2022            247 non-null    float64
 67  2023            245 non-null    float64
 68  2024            236 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [49]:
df_electricity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            187 non-null    float64
 35  1991            187 non-null    float64
 36  1992            188 non-null    float64
 37  1993            188 non-null    float64
 38  1994            188 non-null    float64
 39  1995            189 non-null    float64
 40  1996            189 non-null    float64
 41  1997            189 non-null    float64
 42  1998            189 non-null    float64
 43  1999            189 non-null    float64
 44  2000            192 non-null    float64
 45  2001            192 non-null    float64
 46  2002            192 non-null    float64
 47  2003            192 non-null    float64
 48  2004            192 non-null    float64
 49  2005            193 non-null    float64
 50  2006            193 non-null    float64
 51  2007            193 non-null    float64
 52  2008            193 non-null    float64
 53  2009            193 non-null    float64
 54  2010            193 non-null    float64
 55  2011            193 non-null    float64
 56  2012            194 non-null    float64
 57  2013            194 non-null    float64
 58  2014            194 non-null    float64
 59  2015            193 non-null    float64
 60  2016            193 non-null    float64
 61  2017            193 non-null    float64
 62  2018            193 non-null    float64
 63  2019            193 non-null    float64
 64  2020            193 non-null    float64
 65  2021            193 non-null    float64
 66  2022            193 non-null    float64
 67  2023            192 non-null    float64
 68  2024            51 non-null     float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [50]:
df_owid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7872 entries, 0 to 7871
Data columns (total 4 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Entity                                        7872 non-null   object
 1   Code                                          7030 non-null   object
 2   Year                                          7872 non-null   int64
 3   Share of electricity from low-carbon sources  7872 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 246.1+ KB

In [51]:
df_renewable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 10 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   country                                 188 non-null    object
 1   year                                    188 non-null    int64
 2   installed_capacity_mw                   188 non-null    int64
 3   generation_gwh                          188 non-null    int64
 4   renewable_installed_capacity_mw         188 non-null    int64
 5   renewable_installed_capacity_share_pct  188 non-null    float64
 6   renewable_generation_gwh                188 non-null    int64
 7   renewable_generation_share_pct          187 non-null    float64
 8   renewable_generation_change_pct_points  187 non-null    float64
 9   source_url                              188 non-null    object
dtypes: float64(3), int64(5), object(2)
memory usage: 14.8+ KB

## Clean IEA EV Data

The IEA workbook contains different years, vehicle modes, powertrains, and both historical and projected values. Only historical 2024 country data is selected for the index.

In [52]:
# Keep the 2024 historical EV records needed for the index.
df_iea_2024 = df_iea[df_iea["year"] == 2024].copy()
df_iea_2024 = df_iea_2024[df_iea_2024["category"] == "Historical"]

# Car adoption indicators and public charger indicators are selected separately.
df_iea_2024 = df_iea_2024[
    ((df_iea_2024["parameter"].isin(["EV sales share", "EV stock share"])) &
     (df_iea_2024["mode"] == "Cars") &
     (df_iea_2024["powertrain"] == "EV")) |
    ((df_iea_2024["parameter"] == "EV stock") &
     (df_iea_2024["mode"] == "Cars") &
     (df_iea_2024["powertrain"].isin(["BEV", "PHEV", "FCEV"]))) |
    ((df_iea_2024["parameter"] == "EV charging points") &
     (df_iea_2024["mode"] == "EV") &
     (df_iea_2024["powertrain"].isin(["Publicly available slow", "Publicly available fast"])))
]

df_iea_2024.head()

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
27,World,Historical,EV stock,Cars,BEV,2024,Vehicles,39000000.0,_World
43,Asia Pacific,Historical,EV stock,Cars,BEV,2024,Vehicles,24000000.0,Aggregate_sales_stock
44,China,Historical,EV stock,Cars,BEV,2024,Vehicles,23000000.0,Other
49,World,Historical,EV stock,Cars,PHEV,2024,Vehicles,19000000.0,_World
72,Asia Pacific,Historical,EV stock,Cars,PHEV,2024,Vehicles,11000000.0,Aggregate_sales_stock

In [53]:
# Check that the selected IEA indicators are the ones needed.
df_iea_2024[["parameter", "mode", "powertrain"]].value_counts()

parameter           mode  powertrain
EV sales share      Cars  EV                         61
EV stock            Cars  PHEV                       48
                          BEV                        48
EV stock share      Cars  EV                         48
EV charging points  EV    Publicly available fast    43
                          Publicly available slow    43
EV stock            Cars  FCEV                       35
Name: count, dtype: int64

In [54]:
# EV sales share for cars
df_sales_share = df_iea_2024[
    (df_iea_2024["parameter"] == "EV sales share") &
    (df_iea_2024["mode"] == "Cars")
][["region_country", "value"]].copy()
df_sales_share = df_sales_share.rename(columns={"value": "EV_sales_share"})

# EV stock share for cars
df_stock_share = df_iea_2024[
    (df_iea_2024["parameter"] == "EV stock share") &
    (df_iea_2024["mode"] == "Cars")
][["region_country", "value"]].copy()
df_stock_share = df_stock_share.rename(columns={"value": "EV_stock_share"})

# EV stock is split by powertrain, so BEV, PHEV, and FCEV are summed.
df_stock = df_iea_2024[
    (df_iea_2024["parameter"] == "EV stock") &
    (df_iea_2024["mode"] == "Cars")
].groupby("region_country", as_index=False)["value"].sum()
df_stock = df_stock.rename(columns={"value": "EV_stock"})

# Public slow charging points
df_slow = df_iea_2024[
    (df_iea_2024["parameter"] == "EV charging points") &
    (df_iea_2024["powertrain"] == "Publicly available slow")
][["region_country", "value"]].copy()
df_slow = df_slow.rename(columns={"value": "Public_slow_chargers"})

# Public fast charging points
df_fast = df_iea_2024[
    (df_iea_2024["parameter"] == "EV charging points") &
    (df_iea_2024["powertrain"] == "Publicly available fast")
][["region_country", "value"]].copy()
df_fast = df_fast.rename(columns={"value": "Public_fast_chargers"})

In [55]:
# Merge the selected IEA indicators into one country-level EV table.
df_iea_clean = df_sales_share.copy()
df_iea_clean = pd.merge(df_iea_clean, df_stock_share, on="region_country", how="outer")
df_iea_clean = pd.merge(df_iea_clean, df_stock, on="region_country", how="outer")
df_iea_clean = pd.merge(df_iea_clean, df_slow, on="region_country", how="outer")
df_iea_clean = pd.merge(df_iea_clean, df_fast, on="region_country", how="outer")

df_iea_clean = df_iea_clean.rename(columns={"region_country": "Country"})

df_iea_clean.head()

,Country,EV_sales_share,EV_stock_share,EV_stock,Public_slow_chargers,Public_fast_chargers
0,Africa,0.62,0.054,19203.0,NaN,NaN
1,Asia Pacific,31.00,6.700,35045000.0,NaN,NaN
2,Australia,13.00,1.900,302089.0,2800.0,3900.0
3,Austria,24.00,5.300,275062.0,21000.0,6300.0
4,Belgium,43.00,11.000,670100.0,72000.0,2600.0

## Inspect IEA Country and Region Values

Before removing non-country rows, the unique values from the IEA country field are printed. This shows which entries are actual countries and which entries are regional aggregates.

In [56]:
print("Unique IEA country and region values before filtering:")

for country in sorted(df_iea_clean["Country"].dropna().unique()):
    print(country)

print("\nTotal unique IEA values before filtering:", df_iea_clean["Country"].nunique())

Unique IEA country and region values before filtering:
Africa
Asia Pacific
Australia
Austria
Belgium
Brazil
Bulgaria
Canada
Central and South America
Chile
China
Colombia
Costa Rica
Croatia
Cyprus
Czech Republic
Denmark
EU27
Estonia
Europe
Finland
France
Germany
Greece
Hungary
Iceland
India
Indonesia
Ireland
Israel
Italy
Japan
Jordan
Korea
Latvia
Lithuania
Luxembourg
Malaysia
Mexico
Middle East and Caspian
Netherlands
New Zealand
North America
Norway
Poland
Portugal
Rest of the world
Romania
Russia
Slovakia
Slovenia
South Africa
Spain
Sweden
Switzerland
Thailand
Turkiye
USA
United Kingdom
Uzbekistan
Viet Nam
World

Total unique IEA values before filtering: 62

## Remove Non-Country Rows from IEA Data

The IEA file includes aggregate regions such as World and Europe. These are removed because the final index compares countries.

In [57]:
aggregate_rows = [
    "World", "Europe", "European Union", "Asia Pacific", "Rest of the world",
    "Other Europe", "Other Asia", "Central and South America",
    "Middle East", "Africa", "North America"
]

df_iea_clean = df_iea_clean[~df_iea_clean["Country"].isin(aggregate_rows)].copy()

print("Countries after removing aggregates:", df_iea_clean.shape[0])
df_iea_clean.head()

Countries after removing aggregates: 55

,Country,EV_sales_share,EV_stock_share,EV_stock,Public_slow_chargers,Public_fast_chargers
2,Australia,13.0,1.9,302089.0,2800.0,3900.0
3,Austria,24.0,5.3,275062.0,21000.0,6300.0
4,Belgium,43.0,11.0,670100.0,72000.0,2600.0
5,Brazil,6.4,0.7,214003.0,12000.0,600.0
6,Bulgaria,5.0,NaN,NaN,NaN,NaN

## Clean World Bank Data

The index uses 2024 as the main year. For supporting World Bank indicators, the closest available previous year is used where 2024 is missing. This follows the same logic as using the most recent available value to avoid unnecessary country loss.

In [ ]:
# Use the closest available year up to 2024 for World Bank indicators.
def get_closest_world_bank_value(data, indicator_name, target_year=2024):
    year_columns = [column for column in data.columns if column.isdigit()]
    year_columns = [column for column in year_columns if int(column) <= target_year]
    year_columns = sorted(year_columns, reverse=True)
    
    rows = []
    
    for index, row in data.iterrows():
        selected_value = np.nan
        selected_year = np.nan
        
        for year in year_columns:
            if pd.notnull(row[year]):
                selected_value = row[year]
                selected_year = int(year)
                break
        
        rows.append({
            "Country": row["Country Name"],
            "Country_code": row["Country Code"],
            indicator_name: selected_value,
            indicator_name + "_year": selected_year
        })
    
    return pd.DataFrame(rows)

In [ ]:
# Create the cleaned population table.
df_population_clean = get_closest_world_bank_value(df_population, "Population", 2024)
df_population_clean.head()

In [ ]:
# Create the cleaned GDP per capita table.
df_gdp_clean = get_closest_world_bank_value(df_gdp, "GDP_per_capita_PPP", 2024)
df_gdp_clean.head()

In [ ]:
# Create the cleaned electric power consumption table.
df_electricity_clean = get_closest_world_bank_value(df_electricity, "Electric_power_consumption", 2024)
df_electricity_clean.head()